version: "3.8"

services:
  test:
    build:
      context: .
      dockerfile: dockerfile
      target: test

  pre-commit:
    build:
      context: .
      dockerfile: dockerfile
      target: pre-commit

  build-wheel:
    build:
      context: .
      dockerfile: dockerfile
      target: build-wheel

  install-wheel:
    build:
      context: .
      dockerfile: dockerfile
      target: install-wheel
