version: "3.8"

services:

  test:
    build:
      context: .
      dockerfile: dockerfile
      target: test
    platform: linux/x86_64

  wheel:
    build:
      context: .
      dockerfile: dockerfile
      target: wheel
    platform: linux/x86_64

  pre-commit:
    build:
      context: .
      dockerfile: dockerfile
      target: pre-commit
    platform: linux/x86_64

  test-wheel-install:
    build:
      context: .
      dockerfile: dockerfile
      target: test-wheel-install
    platform: linux/x86_64
