name: release

on:
  release:
    types:
    - published

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2.3.4

    - name: publish
      run: |
        docker-compose run build
        for EACH in ./dist/*.whl; do
          echo "${{ github.event.release.upload_url }}=$(basename $EACH)"
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: $(file -b --mime-type $EACH)" \
            -T "$EACH" \
            "${{ github.event.release.upload_url }}=$(basename $EACH)"
        done;

    - name: Publish to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@main
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
